services:
  building_api:
    build:
      dockerfile: Dockerfiles/Dockerfile.BuildingAPI
    restart: always
    ports:
      - 3000:8080
    depends_on:
      message_broker:
        condition: service_started
      buildings_database:
        condition: service_started
      building_api_migrations:
        condition: service_completed_successfully

  building_api_migrations:
    build:
      dockerfile: Dockerfiles/Dockerfile.BuildingAPI-migrations
    depends_on:
      buildings_database:
        condition: service_started

  classroom_api:
    build:
      dockerfile: Dockerfiles/Dockerfile.ClassroomAPI
    restart: always
    ports:
      - 3001:8080
    depends_on:
      message_broker:
        condition: service_started
      classrooms_database:
        condition: service_started
      classrooms_api_migrations:
        condition: service_completed_successfully

  classrooms_api_migrations:
    build:
      dockerfile: Dockerfiles/Dockerfile.ClassroomAPI-migrations
    depends_on:
      buildings_database:
        condition: service_started

  message_broker:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 15673:15672
    volumes:
      - message-broker-data:/var/lib/rabbitmq/
      - message-broker-log:/var/log/rabbitmq

  buildings_database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=buildings
      - POSTGRES_USER=buildings_user
      - POSTGRES_PASSWORD=buildings_pass
    volumes:
      - buildings-database:/var/lib/postgresql/data

  classrooms_database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=classrooms
      - POSTGRES_USER=classrooms_user
      - POSTGRES_PASSWORD=classrooms_pass
    volumes:
      - classrooms-database:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  message-broker-data:
    driver: local
  message-broker-log:
    driver: local
  buildings-database:
    driver: local
  classrooms-database:
    driver: local
